### ISSUE TITLE
Question: Is it possible to control sidebar position for multiple sections/types independently?

### ISSUE THREAD

**Issue by a-luna** [Vimux/Mainroad#125]
On my site, I have two content types: post and projects. In the config file, the settings below will control the sidebar position for both types:

```toml
[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
```
Is it possible through some combination of creating custom layouts/front matter variables to achieve the following layouts?

home page => sidebar displays on right
 "post" list page => sidebar displays on right
"post" single page => sidebar displays on right
 "projects" list page => sidebar hidden
"projects" single page => sidebar displays on right

I originally wanted to remove the sidebar from both list and single page "projects" pages, so I created my own base template in layouts/projects, and removed the code that renders the sidebar (layouts/projects/baseof.html). This did exactly what I wanted.

I later thought it might be nice to show the sidebar on the single page "projects" pages but I couldn't figure out how to do this while still hiding the sidebar on the "projects" list page AND displaying the sidebar on the "post" list page.

If I revert the changes to layouts/projects/baseof.html and include the code that renders the sidebar, I make the sidebar configuration as shown below:

```toml
[Params.sidebar]
  home = "right" # Configure layout for home page
  list = false  # Configure layout for list pages
  single = "right" # Configure layout for single pages
```
This doesn't do what I want since all list pages (categories, tags, etc) now hide the sidebar. I assume this would be a feature request, but is it possible to configure the sidebar position separately for each content type in the config.toml?

```toml
[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure default layout for list pages
  single = "right" # Configure default layout for single pages

[Params.post.sidebar]
  list = "right"   # Configure layout for post list pages
  single = "right" # Configure layout for post single pages

[Params.project.sidebar]
  list = false   # Configure layout for project list pages
  single = "right" # Configure layout for project single pages

```

**Comment by Vimux** [comment]
In your particular case, you can do this:

Config.toml:

```toml
[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = "right" # Configure layout for single pages
```

content/projects/_index.md:

```yaml
---
sidebar: false
---
```

***

> I later thought it might be nice to show the sidebar on the single page "projects" pages but I couldn't figure out how to do this

https://gohugo.io/templates/lookup-order/#hugo-layouts-lookup-rules

`layouts/projects/list.html.html`: Custom list layout for "projects"
`layouts/projects/single.html.html`: Custom single layout for "projects"

I have not tested it but it should work too.
