### ISSUE TITLE
provide widgets configs for different pages

### ISSUE THREAD

**Issue by elonzh** [Vimux/Mainroad#196]
Sidebar with widgets is a great idea, but currently, we only can enable sidebar separately for different pages.

It's inconvenient if we want to customize the sidebar layout or write widgets for different pages.

Maybe we can add `home_widgets`, `list_widgets`, `single_widgets` params for `Params.sidebar`, the theme use `home_widgets`, `list_widgets` or `single_widgets` if it is specified, else use `widgets` as default.

```toml
[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

  home_widgets = []
  list_widgets = []
  single_widgets = []
```
