### ISSUE TITLE
Post has the function to return to the main page.

### ISSUE THREAD

**Issue by Tomas688** [Vimux/Mainroad#75]
Hi,

Could you give me an advice please?
I have already asked here: https://discourse.gohugo.io/t/post-as-the-main-menu-button-same-function/13870/3

**Comment by Vimux** [comment]
Honestly, I do not fully understand what you need. Did you try something like that:

```yaml
---
title: Migrate to Hugo from Jekyll
date: 2014-03-10
linktitle: Migrating from Jekyll
menu:
  main:
    url: /
    name: Jekyll migration
    weight: 10
---
```

 If you can describe what you need, I'll try to help you.
