### ISSUE TITLE
the singlepage don't display the sidebar

### ISSUE THREAD

**Issue by showo** [Vimux/Mainroad#90]
copy the new theme's content to vicinal config.toml,the singlepage don't display the sidebar.

> 
[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = true  # Configure layout for single pages
  #Enable widgets in given order
  widgets = [ "recent", "categories", "taglist", "social"] #"search"

how to set up ?

**Comment by Vimux** [comment]
```toml
[Params.sidebar]
home = "right"
list = "right"
single = "right"
```
